#pragma once

/// @file Scene.h
/// @brief Scene 層の公開ヘッダをまとめて取り込む umbrella

#include "Framework/Scene/AssetManager.h"
#include "Framework/Scene/CameraSubsystem.h"
#include "Framework/Scene/Component.h"
#include "Framework/Scene/ComponentRegistry.h"
#include "Framework/Scene/Components/BoxColliderComponent.h"
#include "Framework/Scene/Components/CameraBrainComponent.h"
#include "Framework/Scene/Components/CameraComponent.h"
#include "Framework/Scene/Components/CapsuleColliderComponent.h"
#include "Framework/Scene/Components/CharacterMovementComponent.h"
#include "Framework/Scene/Components/EditorCameraComponent.h"
#include "Framework/Scene/Components/HazardComponent.h"
#include "Framework/Scene/Components/MeshColliderComponent.h"
#include "Framework/Scene/Components/MeshRendererComponent.h"
#include "Framework/Scene/Components/PickupComponent.h"
#include "Framework/Scene/Components/PlacedVirtualCamera.h"
#include "Framework/Scene/Components/PlayerInputComponent.h"
#include "Framework/Scene/Components/ShadowComponent.h"
#include "Framework/Scene/Components/SkeletalAnimationComponent.h"
#include "Framework/Scene/Components/SlopeColliderComponent.h"
#include "Framework/Scene/Components/SphereColliderComponent.h"
#include "Framework/Scene/Components/ThirdPersonFollowComponent.h"
#include "Framework/Scene/Components/VirtualCameraComponent.h"
#include "Framework/Scene/EnvironmentSubsystem.h"
#include "Framework/Scene/GameObject.h"
#include "Framework/Scene/IRenderable.h"
#include "Framework/Scene/ObjectRef.h"
#include "Framework/Scene/ObjectRefSubsystem.h"
#include "Framework/Scene/Reflection.h"
#include "Framework/Scene/ReflectionJson.h"
#include "Framework/Scene/RenderContext.h"
#include "Framework/Scene/SceneBase.h"
#include "Framework/Scene/SceneManager.h"
#include "Framework/Scene/SceneSubsystem.h"
#include "Framework/Scene/SubsystemRegistry.h"
#include "Framework/Scene/Transform.h"
